---
title: "STA 210: Regression Analysis"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|           Week            | Date          | Topic                                                                                                                     |                             Prepare                             |                                   Slides                                   |                                                      AE                                                      |                                                                                                   Lab                                                                                                   |                                                                                       HW                                                                                       |                            Exam                            |                                                                                                                                                                                                                                                                                                                       Project                                                                                                                                                                                                                                                                                                                        |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](/weeks/week-1.html)  | Wed, May 11   |                                                                                                                           |  [📖](/weeks/week-1.html#prepare){aria-label="Week 1 summary"}  |  [🖥️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"}  |     [📋](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"}      |                                                               [💻](/labs/lab-0.html "Lab instructions"){aria-label="Lab 0 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 1 - Meet the toolkit                                                                                                  |                                                                 |      [🖥️](/slides/lab-1.html "Lab slides"){aria-label="Lab 1 slides"}      |                                                                                                              |                                                               [💻](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, May 12  | Simple linear regression (SLR)                                                                                            |  [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"}  |  [🖥️](/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"}  |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, May 13   | SLR: Model fitting in R with tidymodels                                                                                   |                                                                 |  [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"}  |   [📋](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"}   |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: HW 5                                                                                                            |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-5.html){aria-label="HW 5 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 1 + AE 0                                                                                                         |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-1.html "Lab instructions"){aria-label="Lab 1 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-1-key.pdf){aria-label="Lab 1 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, May 15   | Due: AE 1                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|  [2](/weeks/week-2.html)  | Mon, May 16   | SLR: Prediction + model evaluation                                                                                        |  [📖](/weeks/week-3.html#prepare){aria-label="Week 3 summary"}  |  [🖥️](/slides/lec-4.html "Lecture slides"){aria-label="Lecture 4 slides"}  |   [📋](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"}   |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: HW 1                                                                                                            |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-1.html){aria-label="HW 1 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Tue, May 17   | SLR: Simulation-based inference                                                                                           |                                                                 |    [🖥️](/slides/lec-5.html "Lab slides"){aria-label="Lecture 5 slides"}    |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Wed, May 18   | SLR: Mathematical models for inference                                                                                    |  [📖](/weeks/week-4.html#prepare){aria-label="Week 4 summary"}  |  [🖥️](/slides/lec-6.html "Lecture slides"){aria-label="Lecture 6 slides"}  |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 2 - College scorecard                                                                                                 |                                                                 |      [🖥️](/slides/lab-2.pdf "Lab slides"){aria-label="Lab 2 slides"}       |                                                                                                              |                                                               [💻](/labs/lab-2.html "Lab instructions"){aria-label="Lab 2 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: HW 1 + AE 2                                                                                                          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         | [✍️](/hw/hw-1.html){aria-label="HW 1 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-1-key.pdf){aria-label="HW 1 key"} |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, May 19  | SLR: Model diagnostics                                                                                                    |                                                                 |  [🖥️](/slides/lec-7.html "Lecture slides"){aria-label="Lecture 7 slides"}  |   [📋](/ae/ae-3-duke-forest.html "Application exercise"){aria-label="Application Exercise 3 instructions"}   |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, May 20   | Exam 1 review                                                                                                             |                                                                 |  [🖥️](/slides/lec-9.html "Lecture slides"){aria-label="Lecture 9 slides"}  |  [📋](/ae/ae-4-exam-1-review.html "Application exercise"){aria-label="Application Exercise 4 instructions"}  |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: Exam 1                                                                                                          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-1.html){aria-label="Exam 1 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 2 + AE 3                                                                                                         |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-2.html "Lab instructions"){aria-label="Lab 2 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-2-key.pdf){aria-label="Lab 2 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, May 22   | Due: AE 4                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [3](/weeks/week-3.html)\* | Mon, May 23   | Multiple linear regression (MLR)                                                                                          |  [📖](/weeks/week-5.html#prepare){aria-label="Week 5 summary"}  |  [🖥️](/slides/lec-8.html "Lecture slides"){aria-label="Lecture 8 slides"}  |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab: [Project topic ideas](https://sta210-s22.github.io/website/project-description.html#topic-ideas)                     |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                  [📂](https://sta210-s22.github.io/website/project-description.html#topic-ideas){aria-label="Project topic ideas"}                                                                                                                                                                                                                                                                   |
|                           |               | Due: Exam 1                                                                                                               |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-1.html){aria-label="Exam 1 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Tue, May 24   | MLR: Types of predictors                                                                                                  |  [📖](/weeks/week-6.html#prepare){aria-label="Week 6 summary"}  | [🖥️](/slides/lec-10.html "Lecture slides"){aria-label="Lecture 10 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Wed, May 25   | MLR: Model comparison                                                                                                     |                                                                 | [🖥️](/slides/lec-11.html "Lecture slides"){aria-label="Lecture 11 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: HW 2                                                                                                            |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-2.html){aria-label="HW 2 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 3 - Coffee ratings                                                                                                    |                                                                 |      [🖥️](/slides/lab-3.html "Lab slides"){aria-label="Lab 3 slides"}      |                                                                                                              |                                                               [💻](/labs/lab-3.html "Lab instructions"){aria-label="Lab 3 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, May 26  | MLR: Feature engineering                                                                                                  |  [📖](/weeks/week-7.html#prepare){aria-label="Week 7 summary"}  | [🖥️](/slides/lec-12.html "Lecture slides"){aria-label="Lecture 12 slides"} |   [📋](/ae/ae-5-the-office.html "Application exercise"){aria-label="Application Exercise 5 instructions"}    |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, May 27   | MLR: Feature engineering                                                                                                  |                                                                 | [🖥️](/slides/lec-13.html "Lecture slides"){aria-label="Lecture 13 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 3 + AE 5                                                                                                         |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-3.html "Lab instructions"){aria-label="Lab 3 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-3-key.pdf){aria-label="Lab 3 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, May 29   | Due: HW 2 + Project topic ideas                                                                                           |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         | [✍️](/hw/hw-2.html){aria-label="HW 2 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-2-key.pdf){aria-label="HW 2 key"} |                                                            |                                                                                                                                                                                                                                                                  [📂](https://sta210-s22.github.io/website/project-description.html#topic-ideas){aria-label="Project topic ideas"}                                                                                                                                                                                                                                                                   |
|  [4](/weeks/week-4.html)  | Mon, May 30   | Memorial Day holiday                                                                                                      |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Tue, May 31   | MLR: Cross validation                                                                                                     |  [📖](/weeks/week-8.html#prepare){aria-label="Week 8 summary"}  | [🖥️](/slides/lec-14.html "Lecture slides"){aria-label="Lecture 14 slides"} |  [📋](/ae/ae-6-the-office-cv.html "Application exercise"){aria-label="Application Exercise 6 instructions"}  |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Wed, June 1   | MLR: Inference                                                                                                            |  [📖](/weeks/week-9.html#prepare){aria-label="Week 9 summary"}  | [🖥️](/slides/lec-16.html "Lecture slides"){aria-label="Lecture 16 slides"} |   [📋](/ae/ae-8-rail-trail.html "Application exercise"){aria-label="Application Exercise 8 instructions"}    |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 4: The Office                                                                                                         |                                                                 |                                                                            |                                                                                                              |                                                               [💻](/labs/lab-4.html "Lab instructions"){aria-label="Lab 4 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: AE 6                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, June 2  | MLR: Inference conditions + multicollinearity                                                                             |                                                                 | [🖥️](/slides/lec-17.html "Lecture slides"){aria-label="Lecture 17 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, June 3   | Exam 2 review                                                                                                             |                                                                 | [🖥️](/slides/lec-15.html "Lecture slides"){aria-label="Lecture 15 slides"} |  [📋](/ae/ae-7-exam-2-review.html "Application exercise"){aria-label="Application Exercise 7 instructions"}  |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: Exam 2                                                                                                          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-2.html){aria-label="Exam 2 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 4 + AE 7                                                                                                         |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-4.html "Lab instructions"){aria-label="Lab 4 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-4-key.pdf){aria-label="Lab 4 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, June 5   | Due: AE 8                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [5](/weeks/week-5.html)\* | Mon, June 6   | Logistic regression (LR)                                                                                                  | [📖](/weeks/week-10.html#prepare){aria-label="Week 10 summary"} | [🖥️](/slides/lec-18.html "Lecture slides"){aria-label="Lecture 18 slides"} |      [📋](/ae/ae-9-odds.html "Application exercise"){aria-label="Application Exercise 9 instructions"}       |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab: Work on [project proposals](https://sta210-s22.github.io/website/project-description.html#project-proposal)          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                              [📂](https://sta210-s22.github.io/website/project-description.html#project-proposal){aria-label="Project topic proposal"}                                                                                                                                                                                                                                                               |
|                           |               | Due: Exam 2                                                                                                               |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-2.html){aria-label="Exam 2 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Tue, June 7   | Probabilities, odds, and odds ratios                                                                                      |                                                                 | [🖥️](/slides/lec-19.html "Lecture slides"){aria-label="Lecture 19 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Wed, June 8   | LR: Prediction / classification                                                                                           | [📖](/weeks/week-11.html#prepare){aria-label="Week 11 summary"} | [🖥️](/slides/lec-20.html "Lecture slides"){aria-label="Lecture 20 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 5: General Social Survey                                                                                              |                                                                 |                                                                            |                                                                                                              |                                                               [💻](/labs/lab-5.html "Lab instructions"){aria-label="Lab 5 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Project proposals + AE 9                                                                                             |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |             [📂](https://sta210-s22.github.io/website/project-description.html#project-proposal){aria-label="Project topic proposal" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}             |
|                           |               | Released: HW 3                                                                                                            |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-3.html){aria-label="HW 3 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, June 9  | LR: Model comparison                                                                                                      |                                                                 | [🖥️](/slides/lec-21.html "Lecture slides"){aria-label="Lecture 21 slides"} | [📋](/ae/ae-10-flight-delays.html "Application exercise"){aria-label="Application Exercise 10 instructions"} |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, June 10  | LR: Inference + conditions                                                                                                | [📖](/weeks/week-12.html#prepare){aria-label="Week 12 summary"} | [🖥️](/slides/lec-22.html "Lecture slides"){aria-label="Lecture 22 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 5 + AE 10                                                                                                        |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-5.html "Lab instructions"){aria-label="Lab 5 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-5-key.pdf){aria-label="Lab 5 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, June 12  | Due: HW 3                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         | [✍️](/hw/hw-3.html){aria-label="HW 3 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-3-key.pdf){aria-label="HW 3 key"} |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| [6](/weeks/week-6.html)\* | Mon, June 13  | Multinomial Logistic Regression (MultiLR)                                                                                 |                                                                 | [🖥️](/slides/lec-23.html "Lecture slides"){aria-label="Lecture 23 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab: Work on [project drafts](https://sta210-s22.github.io/website/project-description.html#draft-report)                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                [📂](https://sta210-s22.github.io/website/project-description.html#draft-report){aria-label="Project draft report" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                |
|                           |               | Due: HW 5                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-5.html){aria-label="HW 5 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: HW 4                                                                                                            |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                              [✍️](/hw/hw-4.html){aria-label="HW 4 instructions"}                                                               |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Tue, June 14  | MultiLR: Prediction + inferential models                                                                                  | [📖](/weeks/week-13.html#prepare){aria-label="Week 13 summary"} | [🖥️](/slides/lec-24.html "Lecture slides"){aria-label="Lecture 24 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Wed, June 15  | MultiLR: Predictive models                                                                                                |                                                                 | [🖥️](/slides/lec-25.html "Lecture slides"){aria-label="Lecture 25 slides"} |   [📋](/ae/ae-11-volcanoes.html "Application exercise"){aria-label="Application Exercise 11 instructions"}   |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab 6: Why Many Americans Don't Vote                                                                                      |                                                                 |                                                                            |                                                                                                              |                                                               [💻](/labs/lab-6.html "Lab instructions"){aria-label="Lab 6 instructions"}                                                                |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: HW 4                                                                                                                 |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         | [✍️](/hw/hw-4.html){aria-label="HW 4 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-4-key.pdf){aria-label="HW 4 key"} |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           | Thur, June 16 | MultiLR: Predictive models (cont.)                                                                                        | [📖](/weeks/week-14.html#prepare){aria-label="Week 14 summary"} | [🖥️](/slides/lec-26.html "Lecture slides"){aria-label="Lecture 26 slides"} |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Fri, June 17  | Exam 3 review                                                                                                             |                                                                 | [🖥️](/slides/lec-27.html "Lecture slides"){aria-label="Lecture 27 slides"} | [📋](/ae/ae-12-exam-3-review.html "Application exercise"){aria-label="Application Exercise 12 instructions"} |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Wrap-up                                                                                                                   | [📖](/weeks/week-15.html#prepare){aria-label="Week 15 summary"} | [🖥️](/slides/lec-28.html "Lecture slides"){aria-label="Lecture 28 slides"} |                                                      📋                                                      |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Lab 6 +AE 11                                                                                                         |                                                                 |                                                                            |                                                                                                              | [💻](/labs/lab-6.html "Lab instructions"){aria-label="Lab 6 instructions"} [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-6-key.pdf){aria-label="Lab 6 key"} |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Released: Exam 3                                                                                                          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-3.html){aria-label="Exam 3 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Sun, June 19  | Due: Project drafts+ AE 12 + AE 13                                                                                        |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                [📂](https://sta210-s22.github.io/website/project-description.html#draft-report){aria-label="Project draft report" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                |
| [7](/weeks/week-7.html)\* | Mon, June 20  | Juneteenth holiday. No class                                                                                              |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Due: Exam 3                                                                                                               |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                | [✅](/exams/exam-3.html){aria-label="Exam 3 instructions"} |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                           |               | Lab: [Project peer review of drafts](https://sta210-s22.github.io/website/project-description.html#peer-review)           |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                 [📂](https://sta210-s22.github.io/website/project-description.html#peer-review){aria-label="Project peer review" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                 |
|                           |               | Due: Peer review                                                                                                          |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                 [📂](https://sta210-s22.github.io/website/project-description.html#peer-review){aria-label="Project peer review" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}                 |
|                           | Tue, June 21  | Reading day                                                                                                               |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|            \*             | Wed, June 22  | Due: [Video presentation](https://sta210-s22.github.io/website/project-description.html#video-presentation-slides) + repo |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            | [📂](https://sta210-s22.github.io/website/project-description.html#video-presentation-slides){aria-label="Project video presentation and slides" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"} |
|                           |               | Due: [Video comments](https://sta210-s22.github.io/website/project-description.html#presentation-comments)                |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |       [📂](https://sta210-s22.github.io/website/project-description.html#presentation-comments){aria-label="Project presentation comments" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}       |
|                           |               | Due: [Project write-up](https://sta210-s22.github.io/website/project-description.html#written-report)                     |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |              [📂](https://sta210-s22.github.io/website/project-description.html#written-report){aria-label="Project written report" style="text-decoration: underline; color: rgb(133, 153, 0) !important; cursor: text; font-family: \"Lucida Grande\", serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgb(0, 0, 0); background-color: rgb(245, 240, 222);"}              |
|                           | Thur, June 23 | Final grades                                                                                                              |                                                                 |                                                                            |                                                                                                              |                                                                                                                                                                                                         |                                                                                                                                                                                |                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
