---
title: "Lab 1 - Meet the toolkit"
subtitle: "STA 210 - Summer 2022"
footer:  "[yunranchen.github.io/STA210Summer/](https://yunranchen.github.io/STA210Summer/)"
logo: "images/logo.png"
editor: visual
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
execute:
  freeze: auto
---

## **What to expect in lab**

-   Introduction to the lab assignment (\~ 5 - 10 minutes)

-   Work on the lab assignment in teams

-   Lab instructions posted on the [course website](https://yunranchen.github.io/STA210Summer/).

-   Start each lab by finding your assignment repo in the [course GitHub organization](https://github.com/STA210-Summer22)

-   This is where you will find the Quarto document and data to get started

## **Tips**

-   You do not have to finish the lab in class, they will always be due on **Friday at 11:59 pm**. One work strategy is to get through the coding component during lab when a TA or I can help you on the spot, and leave the narrative writing until later.

-   When working in teams, do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.

## Take the survey

-   If you have not yet taken the survey, please finish it right now :

    [Survey](https://duke.qualtrics.com/jfe/form/SV_a2XjEYFcPneNm6y)



## **Check: Do you have the lab-1 repo?**

-   Go to the GitHub course organization: <https://github.com/STA210-Summer22>

-   You should see a repo with the prefix **`lab-1-`** followed by your GitHub username

-   If you do not have this repo, please let me know!

## Demo

**Follow along: **
-   Configure Git using SSH

-   Clone RStudio repo and start new project

-   Render document and produce PDF

-   Update name in YAML

    -   Render, commit, push changes to GitHub

    -   See updates in your GitHub repo

## **When you're done with lab**

-   Make sure all your final changes have been pushed to your GitHub repo

-   Submit the PDF of your responses to [**Gradescope**](https://www.gradescope.com/)

    -   You can access Gradescope through Sakai or the course website

    -   Login using your Duke NetID credentials

## **You're now ready to complete the rest of lab!**

Please "raise your hand" if you need help as you work on the lab
